version: "3"
services:
  bitfoil-nginx:
    container_name: bitfoil-nginx
    build:
      context: nginx
      dockerfile: Dockerfile
      args:
        - NGINX_USER=${NGINX_USER}
        - NGINX_PASSWORD=${NGINX_PASSWORD}
    volumes:
      - ${SYSTEM_PATH}:${SHOP_PATH}
    ports:
      - "${NGINX_PORT}:80"
  bitfoil-indexer:
    container_name: bitfoil-shop
    build:
      context: shop
      dockerfile: Dockerfile
    environment:
      - SHOP_PATH=${SHOP_PATH}
      - SHOP_MOTD=${SHOP_MOTD}
    volumes:
      - ${SYSTEM_PATH}:${SHOP_PATH}
